# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-19 08:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishitem',
            name='item',
        ),
        migrations.RemoveField(
            model_name='wishitem',
            name='wish_user',
        ),
        migrations.AddField(
            model_name='additem',
            name='wish_users',
            field=models.ManyToManyField(to='exam.User'),
        ),
        migrations.AlterField(
            model_name='additem',
            name='add_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='add_user', to='exam.User'),
        ),
        migrations.DeleteModel(
            name='WishItem',
        ),
    ]
